2017-05-05 16:47:40.054 [error] <0.350.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<"set">>, state_orset, <0.197.0>, #Fun<lasp_distribution_backend.38.123925371>, #Fun<lasp_distribution_backend.39.123925371>, <0.352.0>) line 430
2017-05-05 16:47:40.177 [error] <0.350.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<"set">>, state_orset, <0.197.0>, #Fun<lasp_distribution_backend.38.123925371>, #Fun<lasp_distribution_backend.39.123925371>, <0.352.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 16:47:40.264 [error] <0.305.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.350.0> exit with reason no function clause matching lasp_core:update(<<"set">>, state_orset, <0.197.0>, #Fun<lasp_distribution_backend.38.123925371>, #Fun<lasp_distribution_backend.39.123925371>, <0.352.0>) line 430 in context child_terminated
